package org.fountainmc.api;

public final class Blocks {
    private Blocks() {}

    public static final BlockType AIR;
    public static final BlockType STONE;
    public static final BlockType GRASS;
    public static final BlockType DIRT;
    public static final BlockType COBBLESTONE;
    public static final BlockType PLANKS;
    public static final BlockType SAPLING;
    public static final BlockType BEDROCK;
    public static final BlockType FLOWING_WATER;
    public static final BlockType WATER;
    public static final BlockType FLOWING_LAVA;
    public static final BlockType LAVA;
    public static final BlockType SAND;
    public static final BlockType GRAVEL;
    public static final BlockType GOLD_ORE;
    public static final BlockType IRON_ORE;
    public static final BlockType COAL_ORE;
    public static final BlockType LOG;
    public static final BlockType LOG2;
    public static final BlockType LEAVES;
    public static final BlockType LEAVES2;
    public static final BlockType SPONGE;
    public static final BlockType GLASS;
    public static final BlockType LAPIS_ORE;
    public static final BlockType LAPIS_BLOCK;
    public static final BlockType DISPENSER;
    public static final BlockType SANDSTONE;
    public static final BlockType NOTEBLOCK;
    public static final BlockType BED;
    public static final BlockType GOLDEN_RAIL;
    public static final BlockType DETECTOR_RAIL;
    public static final BlockType STICKY_PISTON;
    public static final BlockType WEB;
    public static final BlockType TALLGRASS;
    public static final BlockType DEADBUSH;
    public static final BlockType PISTON;
    public static final BlockType PISTON_HEAD;
    public static final BlockType WOOL;
    public static final BlockType PISTON_EXTENSION;
    public static final BlockType YELLOW_FLOWER;
    public static final BlockType RED_FLOWER;
    public static final BlockType BROWN_MUSHROOM;
    public static final BlockType RED_MUSHROOM;
    public static final BlockType GOLD_BLOCK;
    public static final BlockType IRON_BLOCK;
    public static final BlockType DOUBLE_STONE_SLAB;
    public static final BlockType STONE_SLAB;
    public static final BlockType BRICK_BLOCK;
    public static final BlockType TNT;
    public static final BlockType BOOKSHELF;
    public static final BlockType MOSSY_COBBLESTONE;
    public static final BlockType OBSIDIAN;
    public static final BlockType TORCH;
    public static final BlockType FIRE;
    public static final BlockType MOB_SPAWNER;
    public static final BlockType OAK_STAIRS;
    public static final BlockType CHEST;
    public static final BlockType REDSTONE_WIRE;
    public static final BlockType DIAMOND_ORE;
    public static final BlockType DIAMOND_BLOCK;
    public static final BlockType CRAFTING_TABLE;
    public static final BlockType WHEAT;
    public static final BlockType FARMLAND;
    public static final BlockType FURNACE;
    public static final BlockType LIT_FURNACE;
    public static final BlockType STANDING_SIGN;
    public static final BlockType WOODEN_DOOR;
    public static final BlockType SPRUCE_DOOR;
    public static final BlockType BIRCH_DOOR;
    public static final BlockType JUNGLE_DOOR;
    public static final BlockType ACACIA_DOOR;
    public static final BlockType DARK_OAK_DOOR;
    public static final BlockType LADDER;
    public static final BlockType RAIL;
    public static final BlockType STONE_STAIRS;
    public static final BlockType WALL_SIGN;
    public static final BlockType LEVER;
    public static final BlockType STONE_PRESSURE_PLATE;
    public static final BlockType IRON_DOOR;
    public static final BlockType WOODEN_PRESSURE_PLATE;
    public static final BlockType REDSTONE_ORE;
    public static final BlockType LIT_REDSTONE_ORE;
    public static final BlockType UNLIT_REDSTONE_TORCH;
    public static final BlockType REDSTONE_TORCH;
    public static final BlockType STONE_BUTTON;
    public static final BlockType SNOW_LAYER;
    public static final BlockType ICE;
    public static final BlockType SNOW;
    public static final BlockType CACTUS;
    public static final BlockType CLAY;
    public static final BlockType REEDS;
    public static final BlockType JUKEBOX;
    public static final BlockType FENCE;
    public static final BlockType SPRUCE_FENCE;
    public static final BlockType BIRCH_FENCE;
    public static final BlockType JUNGLE_FENCE;
    public static final BlockType DARK_OAK_FENCE;
    public static final BlockType ACACIA_FENCE;
    public static final BlockType PUMPKIN;
    public static final BlockType NETHERRACK;
    public static final BlockType SOUL_SAND;
    public static final BlockType GLOWSTONE;
    public static final BlockType PORTAL;
    public static final BlockType LIT_PUMPKIN;
    public static final BlockType CAKE;
    public static final BlockType UNPOWERED_REPEATER;
    public static final BlockType POWERED_REPEATER;
    public static final BlockType TRAPDOOR;
    public static final BlockType MONSTER_EGG;
    public static final BlockType STONEBRICK;
    public static final BlockType BROWN_MUSHROOM_BLOCK;
    public static final BlockType RED_MUSHROOM_BLOCK;
    public static final BlockType IRON_BARS;
    public static final BlockType GLASS_PANE;
    public static final BlockType MELON_BLOCK;
    public static final BlockType PUMPKIN_STEM;
    public static final BlockType MELON_STEM;
    public static final BlockType VINE;
    public static final BlockType FENCE_GATE;
    public static final BlockType SPRUCE_FENCE_GATE;
    public static final BlockType BIRCH_FENCE_GATE;
    public static final BlockType JUNGLE_FENCE_GATE;
    public static final BlockType DARK_OAK_FENCE_GATE;
    public static final BlockType ACACIA_FENCE_GATE;
    public static final BlockType BRICK_STAIRS;
    public static final BlockType STONE_BRICK_STAIRS;
    public static final BlockType MYCELIUM;
    public static final BlockType WATERLILY;
    public static final BlockType NETHER_BRICK;
    public static final BlockType NETHER_BRICK_FENCE;
    public static final BlockType NETHER_BRICK_STAIRS;
    public static final BlockType NETHER_WART;
    public static final BlockType ENCHANTING_TABLE;
    public static final BlockType BREWING_STAND;
    public static final BlockType CAULDRON;
    public static final BlockType END_PORTAL;
    public static final BlockType END_PORTAL_FRAME;
    public static final BlockType END_STONE;
    public static final BlockType DRAGON_EGG;
    public static final BlockType REDSTONE_LAMP;
    public static final BlockType LIT_REDSTONE_LAMP;
    public static final BlockType DOUBLE_WOODEN_SLAB;
    public static final BlockType WOODEN_SLAB;
    public static final BlockType COCOA;
    public static final BlockType SANDSTONE_STAIRS;
    public static final BlockType EMERALD_ORE;
    public static final BlockType ENDER_CHEST;
    public static final BlockType TRIPWIRE_HOOK;
    public static final BlockType TRIPWIRE;
    public static final BlockType EMERALD_BLOCK;
    public static final BlockType SPRUCE_STAIRS;
    public static final BlockType BIRCH_STAIRS;
    public static final BlockType JUNGLE_STAIRS;
    public static final BlockType COMMAND_BLOCK;
    public static final BlockType BEACON;
    public static final BlockType COBBLESTONE_WALL;
    public static final BlockType FLOWER_POT;
    public static final BlockType CARROTS;
    public static final BlockType POTATOES;
    public static final BlockType WOODEN_BUTTON;
    public static final BlockType SKULL;
    public static final BlockType ANVIL;
    public static final BlockType TRAPPED_CHEST;
    public static final BlockType LIGHT_WEIGHTED_PRESSURE_PLATE;
    public static final BlockType HEAVY_WEIGHTED_PRESSURE_PLATE;
    public static final BlockType UNPOWERED_COMPARATOR;
    public static final BlockType POWERED_COMPARATOR;
    public static final BlockType DAYLIGHT_DETECTOR;
    public static final BlockType DAYLIGHT_DETECTOR_INVERTED;
    public static final BlockType REDSTONE_BLOCK;
    public static final BlockType QUARTZ_ORE;
    public static final BlockType HOPPER;
    public static final BlockType QUARTZ_BLOCK;
    public static final BlockType QUARTZ_STAIRS;
    public static final BlockType ACTIVATOR_RAIL;
    public static final BlockType DROPPER;
    public static final BlockType STAINED_HARDENED_CLAY;
    public static final BlockType BARRIER;
    public static final BlockType IRON_TRAPDOOR;
    public static final BlockType HAY_BLOCK;
    public static final BlockType CARPET;
    public static final BlockType HARDENED_CLAY;
    public static final BlockType COAL_BLOCK;
    public static final BlockType PACKED_ICE;
    public static final BlockType ACACIA_STAIRS;
    public static final BlockType DARK_OAK_STAIRS;
    public static final BlockType SLIME;
    public static final BlockType DOUBLE_PLANT;
    public static final BlockType STAINED_GLASS;
    public static final BlockType STAINED_GLASS_PANE;
    public static final BlockType PRISMARINE;
    public static final BlockType SEA_LANTERN;
    public static final BlockType STANDING_BANNER;
    public static final BlockType WALL_BANNER;
    public static final BlockType RED_SANDSTONE;
    public static final BlockType RED_SANDSTONE_STAIRS;
    public static final BlockType DOUBLE_STONE_SLAB2;
    public static final BlockType STONE_SLAB2;
    public static final BlockType END_ROD;
    public static final BlockType CHORUS_PLANT;
    public static final BlockType CHORUS_FLOWER;
    public static final BlockType PURPUR_BLOCK;
    public static final BlockType PURPUR_PILLAR;
    public static final BlockType PURPUR_STAIRS;
    public static final BlockType PURPUR_DOUBLE_SLAB;
    public static final BlockType PURPUR_SLAB;
    public static final BlockType END_BRICKS;
    public static final BlockType BEETROOT;
    public static final BlockType GRASS_PATH;
    public static final BlockType END_GATEWAY;
    public static final BlockType FROSTED_ICE;
    public static final BlockType STRUCTURE_BLOCK;

    static {
        AIR = getByName("minecraft:air");
        STONE = getByName("minecraft:stone");
        GRASS = getByName("minecraft:grass");
        DIRT = getByName("minecraft:dirt");
        COBBLESTONE = getByName("minecraft:cobblestone");
        PLANKS = getByName("minecraft:planks");
        SAPLING = getByName("minecraft:sapling");
        BEDROCK = getByName("minecraft:bedrock");
        FLOWING_WATER = getByName("minecraft:flowing_water");
        WATER = getByName("minecraft:water");
        FLOWING_LAVA = getByName("minecraft:flowing_lava");
        LAVA = getByName("minecraft:lava");
        SAND = getByName("minecraft:sand");
        GRAVEL = getByName("minecraft:gravel");
        GOLD_ORE = getByName("minecraft:gold_ore");
        IRON_ORE = getByName("minecraft:iron_ore");
        COAL_ORE = getByName("minecraft:coal_ore");
        LOG = getByName("minecraft:log");
        LOG2 = getByName("minecraft:log2");
        LEAVES = getByName("minecraft:leaves");
        LEAVES2 = getByName("minecraft:leaves2");
        SPONGE = getByName("minecraft:sponge");
        GLASS = getByName("minecraft:glass");
        LAPIS_ORE = getByName("minecraft:lapis_ore");
        LAPIS_BLOCK = getByName("minecraft:lapis_block");
        DISPENSER = getByName("minecraft:dispenser");
        SANDSTONE = getByName("minecraft:sandstone");
        NOTEBLOCK = getByName("minecraft:noteblock");
        BED = getByName("minecraft:bed");
        GOLDEN_RAIL = getByName("minecraft:golden_rail");
        DETECTOR_RAIL = getByName("minecraft:detector_rail");
        STICKY_PISTON = getByName("minecraft:sticky_piston");
        WEB = getByName("minecraft:web");
        TALLGRASS = getByName("minecraft:tallgrass");
        DEADBUSH = getByName("minecraft:deadbush");
        PISTON = getByName("minecraft:piston");
        PISTON_HEAD = getByName("minecraft:piston_head");
        WOOL = getByName("minecraft:wool");
        PISTON_EXTENSION = getByName("minecraft:piston_extension");
        YELLOW_FLOWER = getByName("minecraft:yellow_flower");
        RED_FLOWER = getByName("minecraft:red_flower");
        BROWN_MUSHROOM = getByName("minecraft:brown_mushroom");
        RED_MUSHROOM = getByName("minecraft:red_mushroom");
        GOLD_BLOCK = getByName("minecraft:gold_block");
        IRON_BLOCK = getByName("minecraft:iron_block");
        DOUBLE_STONE_SLAB = getByName("minecraft:double_stone_slab");
        STONE_SLAB = getByName("minecraft:stone_slab");
        BRICK_BLOCK = getByName("minecraft:brick_block");
        TNT = getByName("minecraft:tnt");
        BOOKSHELF = getByName("minecraft:bookshelf");
        MOSSY_COBBLESTONE = getByName("minecraft:mossy_cobblestone");
        OBSIDIAN = getByName("minecraft:obsidian");
        TORCH = getByName("minecraft:torch");
        FIRE = getByName("minecraft:fire");
        MOB_SPAWNER = getByName("minecraft:mob_spawner");
        OAK_STAIRS = getByName("minecraft:oak_stairs");
        CHEST = getByName("minecraft:chest");
        REDSTONE_WIRE = getByName("minecraft:redstone_wire");
        DIAMOND_ORE = getByName("minecraft:diamond_ore");
        DIAMOND_BLOCK = getByName("minecraft:diamond_block");
        CRAFTING_TABLE = getByName("minecraft:crafting_table");
        WHEAT = getByName("minecraft:wheat");
        FARMLAND = getByName("minecraft:farmland");
        FURNACE = getByName("minecraft:furnace");
        LIT_FURNACE = getByName("minecraft:lit_furnace");
        STANDING_SIGN = getByName("minecraft:standing_sign");
        WOODEN_DOOR = getByName("minecraft:wooden_door");
        SPRUCE_DOOR = getByName("minecraft:spruce_door");
        BIRCH_DOOR = getByName("minecraft:birch_door");
        JUNGLE_DOOR = getByName("minecraft:jungle_door");
        ACACIA_DOOR = getByName("minecraft:acacia_door");
        DARK_OAK_DOOR = getByName("minecraft:dark_oak_door");
        LADDER = getByName("minecraft:ladder");
        RAIL = getByName("minecraft:rail");
        STONE_STAIRS = getByName("minecraft:stone_stairs");
        WALL_SIGN = getByName("minecraft:wall_sign");
        LEVER = getByName("minecraft:lever");
        STONE_PRESSURE_PLATE = getByName("minecraft:stone_pressure_plate");
        IRON_DOOR = getByName("minecraft:iron_door");
        WOODEN_PRESSURE_PLATE = getByName("minecraft:wooden_pressure_plate");
        REDSTONE_ORE = getByName("minecraft:redstone_ore");
        LIT_REDSTONE_ORE = getByName("minecraft:lit_redstone_ore");
        UNLIT_REDSTONE_TORCH = getByName("minecraft:unlit_redstone_torch");
        REDSTONE_TORCH = getByName("minecraft:redstone_torch");
        STONE_BUTTON = getByName("minecraft:stone_button");
        SNOW_LAYER = getByName("minecraft:snow_layer");
        ICE = getByName("minecraft:ice");
        SNOW = getByName("minecraft:snow");
        CACTUS = getByName("minecraft:cactus");
        CLAY = getByName("minecraft:clay");
        REEDS = getByName("minecraft:reeds");
        JUKEBOX = getByName("minecraft:jukebox");
        FENCE = getByName("minecraft:fence");
        SPRUCE_FENCE = getByName("minecraft:spruce_fence");
        BIRCH_FENCE = getByName("minecraft:birch_fence");
        JUNGLE_FENCE = getByName("minecraft:jungle_fence");
        DARK_OAK_FENCE = getByName("minecraft:dark_oak_fence");
        ACACIA_FENCE = getByName("minecraft:acacia_fence");
        PUMPKIN = getByName("minecraft:pumpkin");
        NETHERRACK = getByName("minecraft:netherrack");
        SOUL_SAND = getByName("minecraft:soul_sand");
        GLOWSTONE = getByName("minecraft:glowstone");
        PORTAL = getByName("minecraft:portal");
        LIT_PUMPKIN = getByName("minecraft:lit_pumpkin");
        CAKE = getByName("minecraft:cake");
        UNPOWERED_REPEATER = getByName("minecraft:unpowered_repeater");
        POWERED_REPEATER = getByName("minecraft:powered_repeater");
        TRAPDOOR = getByName("minecraft:trapdoor");
        MONSTER_EGG = getByName("minecraft:monster_egg");
        STONEBRICK = getByName("minecraft:stonebrick");
        BROWN_MUSHROOM_BLOCK = getByName("minecraft:brown_mushroom_block");
        RED_MUSHROOM_BLOCK = getByName("minecraft:red_mushroom_block");
        IRON_BARS = getByName("minecraft:iron_bars");
        GLASS_PANE = getByName("minecraft:glass_pane");
        MELON_BLOCK = getByName("minecraft:melon_block");
        PUMPKIN_STEM = getByName("minecraft:pumpkin_stem");
        MELON_STEM = getByName("minecraft:melon_stem");
        VINE = getByName("minecraft:vine");
        FENCE_GATE = getByName("minecraft:fence_gate");
        SPRUCE_FENCE_GATE = getByName("minecraft:spruce_fence_gate");
        BIRCH_FENCE_GATE = getByName("minecraft:birch_fence_gate");
        JUNGLE_FENCE_GATE = getByName("minecraft:jungle_fence_gate");
        DARK_OAK_FENCE_GATE = getByName("minecraft:dark_oak_fence_gate");
        ACACIA_FENCE_GATE = getByName("minecraft:acacia_fence_gate");
        BRICK_STAIRS = getByName("minecraft:brick_stairs");
        STONE_BRICK_STAIRS = getByName("minecraft:stone_brick_stairs");
        MYCELIUM = getByName("minecraft:mycelium");
        WATERLILY = getByName("minecraft:waterlily");
        NETHER_BRICK = getByName("minecraft:nether_brick");
        NETHER_BRICK_FENCE = getByName("minecraft:nether_brick_fence");
        NETHER_BRICK_STAIRS = getByName("minecraft:nether_brick_stairs");
        NETHER_WART = getByName("minecraft:nether_wart");
        ENCHANTING_TABLE = getByName("minecraft:enchanting_table");
        BREWING_STAND = getByName("minecraft:brewing_stand");
        CAULDRON = getByName("minecraft:cauldron");
        END_PORTAL = getByName("minecraft:end_portal");
        END_PORTAL_FRAME = getByName("minecraft:end_portal_frame");
        END_STONE = getByName("minecraft:end_stone");
        DRAGON_EGG = getByName("minecraft:dragon_egg");
        REDSTONE_LAMP = getByName("minecraft:redstone_lamp");
        LIT_REDSTONE_LAMP = getByName("minecraft:lit_redstone_lamp");
        DOUBLE_WOODEN_SLAB = getByName("minecraft:double_wooden_slab");
        WOODEN_SLAB = getByName("minecraft:wooden_slab");
        COCOA = getByName("minecraft:cocoa");
        SANDSTONE_STAIRS = getByName("minecraft:sandstone_stairs");
        EMERALD_ORE = getByName("minecraft:emerald_ore");
        ENDER_CHEST = getByName("minecraft:ender_chest");
        TRIPWIRE_HOOK = getByName("minecraft:tripwire_hook");
        TRIPWIRE = getByName("minecraft:tripwire");
        EMERALD_BLOCK = getByName("minecraft:emerald_block");
        SPRUCE_STAIRS = getByName("minecraft:spruce_stairs");
        BIRCH_STAIRS = getByName("minecraft:birch_stairs");
        JUNGLE_STAIRS = getByName("minecraft:jungle_stairs");
        COMMAND_BLOCK = getByName("minecraft:command_block");
        BEACON = getByName("minecraft:beacon");
        COBBLESTONE_WALL = getByName("minecraft:cobblestone_wall");
        FLOWER_POT = getByName("minecraft:flower_pot");
        CARROTS = getByName("minecraft:carrots");
        POTATOES = getByName("minecraft:potatoes");
        WOODEN_BUTTON = getByName("minecraft:wooden_button");
        SKULL = getByName("minecraft:skull");
        ANVIL = getByName("minecraft:anvil");
        TRAPPED_CHEST = getByName("minecraft:trapped_chest");
        LIGHT_WEIGHTED_PRESSURE_PLATE = getByName("minecraft:light_weighted_pressure_plate");
        HEAVY_WEIGHTED_PRESSURE_PLATE = getByName("minecraft:heavy_weighted_pressure_plate");
        UNPOWERED_COMPARATOR = getByName("minecraft:unpowered_comparator");
        POWERED_COMPARATOR = getByName("minecraft:powered_comparator");
        DAYLIGHT_DETECTOR = getByName("minecraft:daylight_detector");
        DAYLIGHT_DETECTOR_INVERTED = getByName("minecraft:daylight_detector_inverted");
        REDSTONE_BLOCK = getByName("minecraft:redstone_block");
        QUARTZ_ORE = getByName("minecraft:quartz_ore");
        HOPPER = getByName("minecraft:hopper");
        QUARTZ_BLOCK = getByName("minecraft:quartz_block");
        QUARTZ_STAIRS = getByName("minecraft:quartz_stairs");
        ACTIVATOR_RAIL = getByName("minecraft:activator_rail");
        DROPPER = getByName("minecraft:dropper");
        STAINED_HARDENED_CLAY = getByName("minecraft:stained_hardened_clay");
        BARRIER = getByName("minecraft:barrier");
        IRON_TRAPDOOR = getByName("minecraft:iron_trapdoor");
        HAY_BLOCK = getByName("minecraft:hay_block");
        CARPET = getByName("minecraft:carpet");
        HARDENED_CLAY = getByName("minecraft:hardened_clay");
        COAL_BLOCK = getByName("minecraft:coal_block");
        PACKED_ICE = getByName("minecraft:packed_ice");
        ACACIA_STAIRS = getByName("minecraft:acacia_stairs");
        DARK_OAK_STAIRS = getByName("minecraft:dark_oak_stairs");
        SLIME = getByName("minecraft:slime");
        DOUBLE_PLANT = getByName("minecraft:double_plant");
        STAINED_GLASS = getByName("minecraft:stained_glass");
        STAINED_GLASS_PANE = getByName("minecraft:stained_glass_pane");
        PRISMARINE = getByName("minecraft:prismarine");
        SEA_LANTERN = getByName("minecraft:sea_lantern");
        STANDING_BANNER = getByName("minecraft:standing_banner");
        WALL_BANNER = getByName("minecraft:wall_banner");
        RED_SANDSTONE = getByName("minecraft:red_sandstone");
        RED_SANDSTONE_STAIRS = getByName("minecraft:red_sandstone_stairs");
        DOUBLE_STONE_SLAB2 = getByName("minecraft:double_stone_slab2");
        STONE_SLAB2 = getByName("minecraft:stone_slab2");
        END_ROD = getByName("minecraft:end_rod");
        CHORUS_PLANT = getByName("minecraft:chorus_plant");
        CHORUS_FLOWER = getByName("minecraft:chorus_flower");
        PURPUR_BLOCK = getByName("minecraft:purpur_block");
        PURPUR_PILLAR = getByName("minecraft:purpur_pillar");
        PURPUR_STAIRS = getByName("minecraft:purpur_stairs");
        PURPUR_DOUBLE_SLAB = getByName("minecraft:purpur_double_slab");
        PURPUR_SLAB = getByName("minecraft:purpur_slab");
        END_BRICKS = getByName("minecraft:end_bricks");
        BEETROOT = getByName("minecraft:beetroots");
        GRASS_PATH = getByName("minecraft:grass_path");
        END_GATEWAY = getByName("minecraft:end_gateway");
        FROSTED_ICE = getByName("minecraft:frosted_ice");
        STRUCTURE_BLOCK = getByName("minecraft:structure_block");
    }

    public static BlockType getByName(String name) {
        return Fountain.getServer().getBlockType(name);
    }

    public static BlockType getById(int id) {
        return Fountain.getServer().getBlockType(id);
    }

}
